language: "node_js"
sudo: false
node_js:
    - "5"
before_install:
  - "npm install -g bower purescript pulp psa"
script:
  - "bower install"
  # Can't "pulp test", as the Test.Main.main exits with 1; it's not a
  # # test definition so much as an example of use.
  - "pulp build"
